@echo off
set CMAKE_GENERATOR="Visual Studio 16 2019"
set CMAKE_GENERATOR_PLATFORM=Win32
set CMAKE_GENERATOR_TOOLSET=v141_xp
set CMAKE_EXTRA_ARGS=-DNO_ENHANCED_INSTRUCTIONS=ON
call Compile.bat
set CMAKE_EXTRA_PATH=_static
set CMAKE_EXTRA_ARGS=-DFORCE_STATIC_VCRT=ON -DNO_ENHANCED_INSTRUCTIONS=ON
call Compile.bat
if not defined AUTOMATION pause